"""
FORTIFY Backend — test suite.

Unit tests: use FastAPI TestClient, no Docker required.
Integration tests: marked @pytest.mark.integration, require Docker infra.

Run unit tests:
    pytest tests/ -v -m "not integration"

Run all tests (requires Docker):
    pytest tests/ -v
"""
import pytest
from fastapi.testclient import TestClient

from app.main import app
from app.diagnosis import _latency_severity, DiagnosisContext, RuleBasedDiagnosisEngine
from app.experiment import _calculate_improvement, _effective_latency, ResilienceConfig

client = TestClient(app)

# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------

ARCH_PAYLOAD = {
    "architecture_id": "arch_test_001",
    "name": "Test Payment Flow",
    "services": [
        {"id": "gateway", "name": "Gateway", "type": "gateway"},
        {"id": "order", "name": "Order Service", "type": "service"},
        {"id": "payment", "name": "Payment Service", "type": "service"},
    ],
    "connections": [
        {"source": "gateway", "target": "order"},
        {"source": "order", "target": "payment"},
    ],
}


def _ensure_arch():
    client.post("/api/architecture", json=ARCH_PAYLOAD)


# ===========================================================================
# 1. Health
# ===========================================================================

def test_health():
    r = client.get("/api/health")
    assert r.status_code == 200
    assert r.json()["status"] == "ok"
    assert r.json()["service"] == "fortify-backend"


# ===========================================================================
# 2. Architecture
# ===========================================================================

def test_create_architecture():
    r = client.post("/api/architecture", json=ARCH_PAYLOAD)
    assert r.status_code == 200
    assert r.json()["architecture_id"] == "arch_test_001"
    assert r.json()["status"] == "created"


def test_get_architecture():
    _ensure_arch()
    r = client.get("/api/architecture/arch_test_001")
    assert r.status_code == 200
    d = r.json()
    assert d["architecture_id"] == "arch_test_001"
    assert len(d["services"]) == 3
    assert len(d["connections"]) == 2


def test_get_architecture_not_found():
    assert client.get("/api/architecture/no_such_arch").status_code == 404


def test_create_architecture_autogenerated_id():
    payload = {k: v for k, v in ARCH_PAYLOAD.items() if k != "architecture_id"}
    r = client.post("/api/architecture", json=payload)
    assert r.status_code == 200
    assert r.json()["architecture_id"].startswith("arch_")


# ===========================================================================
# 3. Attacks — unit (no Toxiproxy)
# ===========================================================================

def test_invalid_attack_type():
    r = client.post("/api/attacks", json={
        "architecture_id": "arch_test_001", "target": "payment",
        "type": "earthquake", "value": 9000,
    })
    assert r.status_code == 400
    assert "Unsupported" in r.json()["detail"]


def test_invalid_attack_target():
    r = client.post("/api/attacks", json={
        "architecture_id": "arch_test_001", "target": "gateway",
        "type": "latency", "value": 5000,
    })
    assert r.status_code == 400
    assert "payment" in r.json()["detail"]


def test_invalid_latency_value():
    r = client.post("/api/attacks", json={
        "architecture_id": "arch_test_001", "target": "payment",
        "type": "latency", "value": -500,
    })
    assert r.status_code == 400


def test_get_attack_not_found():
    assert client.get("/api/attacks/atk_does_not_exist").status_code == 404


def test_attack_metrics_not_found():
    assert client.get("/api/attacks/atk_does_not_exist/metrics").status_code == 404


# ===========================================================================
# 4. Severity logic — pure unit tests, no HTTP
# ===========================================================================

class TestSeverity:
    """Tests for _latency_severity() directly."""

    # ---- No baseline available (fallback on absolute attack magnitude) ----

    def test_no_baseline_5000ms_is_high(self):
        sev, ev = _latency_severity(5000, 2713.0, None, None, None)
        assert sev == "high"

    def test_no_baseline_2000ms_is_medium(self):
        sev, _ = _latency_severity(2000, 800.0, None, None, None)
        assert sev == "medium"

    def test_no_baseline_500ms_is_low(self):
        sev, _ = _latency_severity(500, 300.0, None, None, None)
        assert sev == "low"

    # ---- P95 uplift rules ----

    def test_p95_over_2x_is_high(self):
        # baseline P95 = 2275, attack P95 = 7315  → ratio ≈ 3.2
        sev, ev = _latency_severity(5000, 2713.0, 1217.1, 7315.0, 2275.0)
        assert sev == "high"
        assert ev["p95_uplift_ratio"] == pytest.approx(3.21, abs=0.05)

    def test_p95_1_5x_with_2000ms_attack_is_medium(self):
        # ratio 1.5 and attack 2000 ms → medium
        sev, _ = _latency_severity(2000, 1500.0, 800.0, 3000.0, 2000.0)
        assert sev == "medium"

    def test_p95_barely_above_1x_is_low(self):
        # ratio 1.1, attack 500 ms → low
        sev, _ = _latency_severity(500, 300.0, 200.0, 1100.0, 1000.0)
        assert sev == "low"

    # ---- Average uplift rules (no P95) ----

    def test_avg_uplift_over_3x_is_high(self):
        sev, ev = _latency_severity(5000, 4000.0, 800.0, None, None)
        assert sev == "high"
        assert ev["avg_uplift_ratio"] == pytest.approx(5.0)

    def test_avg_uplift_2x_with_2000ms_is_medium(self):
        sev, _ = _latency_severity(2000, 2000.0, 1000.0, None, None)
        assert sev == "medium"

    def test_avg_uplift_small_is_low(self):
        sev, _ = _latency_severity(300, 350.0, 300.0, None, None)
        assert sev == "low"

    # ---- Evidence dict completeness ----

    def test_evidence_includes_baseline_and_uplift(self):
        _, ev = _latency_severity(5000, 2713.0, 1217.1, 7315.0, 2275.0)
        assert "baseline_latency_ms" in ev
        assert "avg_uplift_ratio" in ev
        assert "baseline_p95_ms" in ev
        assert "observed_p95_ms" in ev
        assert "p95_uplift_ratio" in ev


# ===========================================================================
# 5. Diagnosis API
# ===========================================================================

def test_diagnosis_legacy_medium():
    r = client.post("/api/diagnosis", json={
        "attack_type": "latency", "target": "payment",
        "attack_value": 5000, "average_latency_ms": 5100.0,
    })
    assert r.status_code == 200
    d = r.json()
    # No baseline → falls back to absolute magnitude → 5000 ms = high
    assert d["severity"] == "high"
    assert "diagnosis_id" in d


def test_diagnosis_low_severity_small_attack():
    r = client.post("/api/diagnosis", json={
        "attack_type": "latency", "target": "payment",
        "attack_value": 200, "average_latency_ms": 190.0,
    })
    assert r.status_code == 200
    assert r.json()["severity"] == "low"


def test_diagnosis_missing_params():
    r = client.post("/api/diagnosis", json={"attack_type": "latency"})
    assert r.status_code == 422


def test_diagnosis_unknown_attack_type():
    r = client.post("/api/diagnosis", json={
        "attack_type": "blackhole", "target": "payment",
        "attack_value": 5000, "average_latency_ms": 5000.0,
    })
    assert r.status_code == 200
    assert r.json()["severity"] == "unknown"


# ===========================================================================
# 6. Recommendations
# ===========================================================================

def test_recommendation_unknown_diagnosis():
    r = client.post("/api/recommendations", json={"diagnosis_id": "diag_unknown"})
    assert r.status_code == 404


def test_recommendation_from_valid_diagnosis():
    diag = client.post("/api/diagnosis", json={
        "attack_type": "latency", "target": "payment",
        "attack_value": 5000, "average_latency_ms": 5100.0,
    }).json()
    r = client.post("/api/recommendations", json={"diagnosis_id": diag["diagnosis_id"]})
    assert r.status_code == 200
    d = r.json()
    assert "recommendation_id" in d
    assert isinstance(d["recommendations"], list)
    assert len(d["recommendations"]) > 0
    for rec in d["recommendations"]:
        assert "title" in rec
        assert "reason" in rec
        assert "strategy" in rec


def test_recommendation_high_severity_has_all_strategies():
    """high severity → all 4 strategies including retry."""
    diag = client.post("/api/diagnosis", json={
        "attack_type": "latency", "target": "payment",
        "attack_value": 5000, "average_latency_ms": 8000.0,
    }).json()
    # Force high severity by patching evidence through an engine call
    engine = RuleBasedDiagnosisEngine()
    ctx = DiagnosisContext("latency", "payment", 5000, 8000.0,
                           baseline_latency_ms=None, observed_p95_ms=None, baseline_p95_ms=None)
    result = engine.diagnose(ctx)
    # 5000ms attack, no baseline → high
    assert result["severity"] == "high"


# ===========================================================================
# 7. Metrics — unit (no Prometheus)
# ===========================================================================

def test_metrics_unknown_service():
    r = client.get("/api/metrics/no_such_service")
    assert r.status_code == 404
    assert "no_such_service" in r.json()["detail"]


# ===========================================================================
# 8. Effective latency calculation (resilience simulation unit tests)
# ===========================================================================

class TestEffectiveLatency:
    """Unit tests for the _effective_latency helper."""

    def test_no_resilience_returns_original(self):
        ms, sim, strat = _effective_latency(5000, None)
        assert ms == 5000
        assert sim is False
        assert strat is None

    def test_timeout_caps_latency(self):
        r = ResilienceConfig(strategy="timeout", timeout_ms=1000)
        ms, sim, strat = _effective_latency(5000, r)
        assert ms == 1000
        assert sim is True
        assert strat == "timeout"

    def test_timeout_below_attack_value_is_capped(self):
        r = ResilienceConfig(strategy="timeout", timeout_ms=500)
        ms, sim, strat = _effective_latency(5000, r)
        assert ms == 500

    def test_timeout_above_attack_value_uses_attack(self):
        # timeout > attack → still use attack (min behaviour)
        r = ResilienceConfig(strategy="timeout", timeout_ms=8000)
        ms, sim, strat = _effective_latency(5000, r)
        assert ms == 5000  # min(5000, 8000)

    def test_circuit_breaker_zeroes_latency(self):
        r = ResilienceConfig(strategy="circuit_breaker", circuit_breaker_threshold_ms=500)
        ms, sim, strat = _effective_latency(5000, r)
        assert ms == 0
        assert sim is True
        assert strat == "circuit_breaker"

    def test_unknown_strategy_falls_back(self):
        r = ResilienceConfig(strategy="pixie_dust")
        ms, sim, strat = _effective_latency(5000, r)
        assert ms == 5000
        assert sim is False


# ===========================================================================
# 9. Comparison calculation
# ===========================================================================

class TestCalculateImprovement:
    """Unit tests for _calculate_improvement."""

    def test_degraded_result(self):
        before = {"average_latency_ms": 100.0, "p95_latency_ms": 200.0}
        after  = {"average_latency_ms": 300.0, "p95_latency_ms": 700.0}
        imp = _calculate_improvement(before, after)
        assert imp["latency_direction"] == "degraded"
        assert imp["latency_change_percent"] == pytest.approx(200.0)
        assert imp["p95_change_percent"] == pytest.approx(250.0)

    def test_improved_result(self):
        before = {"average_latency_ms": 5000.0, "p95_latency_ms": 7000.0}
        after  = {"average_latency_ms": 800.0,  "p95_latency_ms": 1000.0}
        imp = _calculate_improvement(before, after)
        assert imp["latency_direction"] == "improved"
        assert imp["latency_change_percent"] < 0
        assert imp["p95_change_percent"] < 0

    def test_no_before_returns_empty(self):
        imp = _calculate_improvement({}, {"average_latency_ms": 300.0})
        assert imp == {}

    def test_no_after_returns_empty(self):
        imp = _calculate_improvement({"average_latency_ms": 100.0}, {})
        assert imp == {}

    def test_includes_before_after_values(self):
        before = {"average_latency_ms": 100.0}
        after  = {"average_latency_ms": 200.0}
        imp = _calculate_improvement(before, after)
        assert imp["before_avg_latency_ms"] == 100.0
        assert imp["after_avg_latency_ms"] == 200.0


# ===========================================================================
# 10. Experiment — validation (no infrastructure)
# ===========================================================================

def test_experiment_unknown_architecture():
    r = client.post("/api/experiment/run", json={
        "architecture_id": "arch_no_such",
        "attack": {"target": "payment", "type": "latency", "value": 5000},
        "traffic": {"rate": 2, "duration_seconds": 2},
    })
    assert r.status_code == 404
    assert "arch_no_such" in r.json()["detail"]


def test_experiment_unsupported_attack():
    _ensure_arch()
    r = client.post("/api/experiment/run", json={
        "architecture_id": "arch_test_001",
        "attack": {"target": "payment", "type": "blackhole", "value": 0},
        "traffic": {"rate": 2, "duration_seconds": 2},
    })
    assert r.status_code == 400
    assert "blackhole" in r.json()["detail"]


# ===========================================================================
# 11. Retest — validation
# ===========================================================================

def test_retest_unknown_attack():
    _ensure_arch()
    r = client.post("/api/retest", json={
        "architecture_id": "arch_test_001",
        "previous_attack_id": "atk_does_not_exist",
    })
    assert r.status_code == 404


def test_retest_unknown_architecture():
    r = client.post("/api/retest", json={
        "architecture_id": "arch_no_such",
        "previous_attack_id": "atk_does_not_exist",
    })
    assert r.status_code == 404


# ===========================================================================
# 12. Comparison endpoint
# ===========================================================================

def test_comparison_not_found_unknown_attack():
    r = client.get("/api/comparisons/atk_does_not_exist")
    assert r.status_code == 404


# ===========================================================================
# 13. Retest request model — resilience config accepted
# ===========================================================================

def test_retest_request_accepts_resilience_config():
    """Verify the model parses correctly — no infra call needed."""
    from app.experiment import RetestRequest, ResilienceConfig as RC
    req = RetestRequest(
        architecture_id="arch_001",
        previous_attack_id="atk_abc",
        resilience=RC(strategy="timeout", timeout_ms=1000),
    )
    assert req.resilience.strategy == "timeout"
    assert req.resilience.timeout_ms == 1000


def test_retest_request_circuit_breaker_config():
    from app.experiment import RetestRequest, ResilienceConfig as RC
    req = RetestRequest(
        architecture_id="arch_001",
        previous_attack_id="atk_abc",
        resilience=RC(strategy="circuit_breaker", circuit_breaker_threshold_ms=500),
    )
    assert req.resilience.strategy == "circuit_breaker"


# ===========================================================================
# Integration tests — require Docker + running infrastructure
# ===========================================================================

@pytest.mark.integration
def test_integration_metrics_gateway():
    r = client.get("/api/metrics/gateway")
    assert r.status_code == 200
    d = r.json()
    assert d["service"] == "gateway"
    assert "request_count" in d
    assert "average_latency_ms" in d


@pytest.mark.integration
def test_integration_valid_latency_attack():
    _ensure_arch()
    r = client.post("/api/attacks", json={
        "architecture_id": "arch_test_001", "target": "payment",
        "type": "latency", "value": 100,
    })
    assert r.status_code == 200
    d = r.json()
    assert d["status"] == "failure_injected"
    client.delete("/api/attacks/latency")
    assert client.get(f"/api/attacks/{d['attack_id']}").status_code == 200


@pytest.mark.integration
def test_integration_full_experiment_has_all_fields():
    """Experiment result must include all expected top-level fields."""
    _ensure_arch()
    r = client.post("/api/experiment/run", json={
        "architecture_id": "arch_test_001",
        "attack": {"target": "payment", "type": "latency", "value": 2000},
        "traffic": {"rate": 3, "duration_seconds": 5},
    }, timeout=120)
    assert r.status_code == 200
    d = r.json()
    for field in ("status", "attack_id", "diagnosis", "recommendations",
                  "baseline_metrics", "attack_metrics", "traffic"):
        assert field in d, f"Missing field: {field}"
    assert d["status"] == "completed"
    assert isinstance(d["recommendations"], list)
    assert len(d["recommendations"]) > 0


@pytest.mark.integration
def test_integration_severity_with_5000ms_attack():
    """5000 ms attack against real baseline must produce 'high' severity."""
    _ensure_arch()
    r = client.post("/api/experiment/run", json={
        "architecture_id": "arch_test_001",
        "attack": {"target": "payment", "type": "latency", "value": 5000},
        "traffic": {"rate": 3, "duration_seconds": 8},
    }, timeout=180)
    assert r.status_code == 200
    d = r.json()
    assert d["diagnosis"]["severity"] == "high", (
        f"Expected high, got {d['diagnosis']['severity']}. "
        f"Evidence: {d['diagnosis'].get('evidence')}"
    )


@pytest.mark.integration
def test_integration_retest_no_resilience_structure():
    """
    Retest without resilience config: verify the response structure and
    that no resilience strategy was falsely applied.

    We do NOT assert latency_direction because the comparison uses
    before = retest's own fresh baseline vs after = cumulative Prometheus
    average, which includes all prior runs in the session. The direction
    is not deterministic across runs, so asserting "degraded" here would
    be testing Prometheus state, not the application logic.

    The deterministic degraded/improved direction logic is fully covered
    by the unit tests in TestCalculateImprovement.
    """
    _ensure_arch()
    exp = client.post("/api/experiment/run", json={
        "architecture_id": "arch_test_001",
        "attack": {"target": "payment", "type": "latency", "value": 2000},
        "traffic": {"rate": 3, "duration_seconds": 5},
    }, timeout=120).json()
    assert "attack_id" in exp

    rt = client.post("/api/retest", json={
        "architecture_id": "arch_test_001",
        "previous_attack_id": exp["attack_id"],
    }, timeout=120)
    assert rt.status_code == 200
    d = rt.json()

    # All required top-level fields are present
    for field in ("retest_id", "new_attack_id", "status", "simulation_mode",
                  "applied_strategy", "attack", "traffic", "baseline_metrics",
                  "attack_metrics", "diagnosis", "recommendations", "comparison"):
        assert field in d, f"Missing retest field: {field}"

    # No resilience was requested — must not be marked as simulated
    assert d["simulation_mode"] is False
    assert d["applied_strategy"] is None

    # The retest ran the same attack value unchanged
    assert d["attack"]["value"] == exp["attack"]["value"]
    assert d["attack"]["effective_value"] == exp["attack"]["value"]

    # Comparison structure is populated
    cmp = d["comparison"]
    assert cmp["after"] is not None
    assert "improvement" in cmp
    imp = cmp["improvement"]
    # improvement is a dict with a latency_change_percent key; direction may
    # be "improved" or "degraded" depending on cumulative Prometheus state
    assert "latency_change_percent" in imp
    assert "latency_direction" in imp
    assert imp["latency_direction"] in ("improved", "degraded")


@pytest.mark.integration
def test_integration_retest_with_timeout_simulated():
    """
    Retest with a 500ms timeout resilience config.
    Verifies simulation semantics: effective_value is capped, simulation_mode
    is True, comparison is populated. Direction is not asserted for the same
    reason as above — cumulative Prometheus averages are session-dependent.
    """
    _ensure_arch()
    exp = client.post("/api/experiment/run", json={
        "architecture_id": "arch_test_001",
        "attack": {"target": "payment", "type": "latency", "value": 5000},
        "traffic": {"rate": 3, "duration_seconds": 6},
    }, timeout=180).json()

    rt = client.post("/api/retest", json={
        "architecture_id": "arch_test_001",
        "previous_attack_id": exp["attack_id"],
        "resilience": {"strategy": "timeout", "timeout_ms": 500},
    }, timeout=120)
    assert rt.status_code == 200
    d = rt.json()

    # Simulation semantics
    assert d["simulation_mode"] is True
    assert d["applied_strategy"] == "timeout"
    assert d["attack"]["effective_value"] == 500        # capped by timeout_ms
    assert d["attack"]["value"] == 5000                  # original preserved

    cmp = d["comparison"]
    assert cmp["simulation_mode"] is True
    assert cmp["applied_strategy"] == "timeout"
    assert "latency_change_percent" in cmp["improvement"]


@pytest.mark.integration
def test_integration_retest_with_circuit_breaker_simulated():
    """
    Retest with circuit_breaker: effective_value = 0, simulation_mode = True.
    Shares the experiment set up by the timeout test when run in sequence,
    but is independent so it creates its own to avoid ordering dependence.
    """
    _ensure_arch()
    exp = client.post("/api/experiment/run", json={
        "architecture_id": "arch_test_001",
        "attack": {"target": "payment", "type": "latency", "value": 5000},
        "traffic": {"rate": 3, "duration_seconds": 6},
    }, timeout=180).json()

    rt = client.post("/api/retest", json={
        "architecture_id": "arch_test_001",
        "previous_attack_id": exp["attack_id"],
        "resilience": {"strategy": "circuit_breaker"},
    }, timeout=120)
    assert rt.status_code == 200
    d = rt.json()
    assert d["simulation_mode"] is True
    assert d["applied_strategy"] == "circuit_breaker"
    assert d["attack"]["effective_value"] == 0
    assert d["attack"]["value"] == 5000


@pytest.mark.integration
def test_integration_comparison_endpoint_structure():
    """
    GET /api/comparisons/{attack_id} returns the correct structure after a retest.
    Reuses the same experiment+retest as the no-resilience test to avoid
    an extra full experiment run.
    """
    _ensure_arch()
    exp = client.post("/api/experiment/run", json={
        "architecture_id": "arch_test_001",
        "attack": {"target": "payment", "type": "latency", "value": 2000},
        "traffic": {"rate": 3, "duration_seconds": 5},
    }, timeout=120).json()

    client.post("/api/retest", json={
        "architecture_id": "arch_test_001",
        "previous_attack_id": exp["attack_id"],
    }, timeout=120)

    cmp = client.get(f"/api/comparisons/{exp['attack_id']}").json()
    assert "before" in cmp
    assert "after" in cmp
    assert cmp["after"] is not None
    assert "improvement" in cmp
    assert "latency_change_percent" in cmp["improvement"]
    # direction exists and is one of the valid values
    assert cmp["improvement"]["latency_direction"] in ("improved", "degraded")
