global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:5000"]
    metrics_path: /metrics

  - job_name: "order"
    static_configs:
      - targets: ["order:5001"]
    metrics_path: /metrics

  - job_name: "payment"
    static_configs:
      - targets: ["payment:5002"]
    metrics_path: /metrics
